# Generated by cucumber-sinatra. (2013-08-18 16:55:04 -0400)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'world.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Sphere

class SphereWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  SphereWorld.new
end
